apiVersion: apps/v1
kind: Deployment

metadata:
  name: eth-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: eth-backend

  template:
    metadata:
      labels:
        app: eth-backend

    spec:
      containers:
        - name: eth-backend
          image: eth-backend-app:latest
          imagePullPolicy: Never