apiVersion: apps/v1
kind: Deployment

metadata:
  name: eth-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: eth-backend

  template:
    metadata:
      labels:
        app: eth-backend

    spec:
      containers:
        - name: eth-backend
          image: eth-backend-app:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: eth-backend-config
            - secretRef:
                name: eth-backend-secret

          ports: 
            - containerPort: 8080

          startupProbe:
            httpGet:
              path: /health/startup
              port: 8080
            failureThreshold: 30
            periodSeconds: 2

          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            failureThreshold: 3
            timeoutSeconds: 2
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2